export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET';
export const GET_NUMBERS_BASKET = 'GET_NUMBERS_BASKET';
export const ADD_PRODUCT_WISHLIST = 'ADD_PRODUCT_WISHLIST';
export const GET_NUMBERS_WISHLIST = 'GET_NUMBERS_WISHLIST';

